# Theme
remote_theme: 'epidrome/cover-card'

# Title and tag line
title: 'bunga test'
description: 'hey there!'

# Images
avatar: 'avatar1.jpg'
background: 'background.jpg'
favicon: 'favicon.ico'

# Online profiles
twitter: '@bungab'
#youtube: ''
#github-user: ''
#gitlab-user: ''
#codepen: ''
#steam: ''
#soundcloud: ''
#lastfm: ''
#stack-overflow: ''
#reddit: ''
#medium:  ''
#tumblr: ''
#blog_url: ''
#email: ''
#messenger: ''
emailform: 'https://kontactr.com/user/xxxxxxxxxx'

# Advanced settings
plugins:
  - jekyll-remote-theme
